apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-cng1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-cng1
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-cng1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-cng1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-cng1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-itwz-tenant/rhtap-demo-app/hacbs-test-project-cng1@sha256:9ecaba43aa47497f006b6b0c57e009ee8101547f570cf216f4f198d2e1670f74
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
